spring:
  datasource:
    url:jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
      username:root
        gitpassword:admin
          driver_class_name:com.mysql.jdbc.Driver
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
