spring:
  datasource:
    url:jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
      username:root
        password:admin
          driver_class_name:com.Mysql.jdbc.Driver
    jpa:
    hibernate:
      naming:
        physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl